### ISSUE TITLE
Line 13: File/Folder Confusion + Fork

### ISSUE THREAD

**Issue by Direcious** [spacerainbow000/Zendesk-SLA-Board#9]
I am attempting to ./startserver, and shortly after I receive the response which includes these errors:

`./pullSLAs: fork: Resource temporarily unavailable`

`cat: tmpl/*: No such file or directory`

`./pullSLAs: line 13: /Users/_/Zendesk-SLA-Board/tmpd/: Is a directory`

`(23) Failed writing body`

I'm not sure how to proceed in order to get the .html page to display a populated dashboard.

**Comment by spacerainbow000** [comment]
are u on rhel? forking errors mean your machine isn't configured to allow more than a certain threshold of forked processes
u can change /etc/security/limits.d/90-nproc.conf either for the user you are running it from or for every user -- double or triple the number of allowed forks
"cat: tmpl/*: No such file or directory" shows up on a first run, it's an irrelevant error that for some reason refuses to go to a log file no matter how hard I tee, same with the rest of those errors they can be safely ignored. your terminal can for sure fill up with them though if you run the board from like a terminal emulator or something, so either run it as a daemon or send it to a new gnu screen (dumb way to run anything really but it works)

**Comment by Direcious** [comment]
Not rhel, I'm on MacOS. I see, so the forking error is now fixed for myself, the other errors are still appearing but I am currently ignoring them. Unfortunately after following the instructions. The server still starts, but the dashboard never gets populated with our ticket data. To clarify, for the 3 files being created (without file extensions, right ?):

creds should look like a@b.c
target should look like xxx.zendesk.com
token should be the zendesk users token

Is this correct ? Or maybe my syntax is off which is making the dashboard fail to fetch data.

**Comment by spacerainbow000** [comment]
that looks right -- the token will be an API token you generate in the admin portion of the zendesk UI. Make sure there are no spaces or line breaks in it. You can test to see how far in the process by manually running some commands from the scripts. try:
```
TOKEN=$(cat token) ; CREDENTIALS=$(cat creds) ; TARGET=$(cat target) ;
curl -s -u $CREDENTIALS/token:$TOKEN "https://$TARGET/api/v2/search.json?include=" -G --data-urlencode "query=type:ticket status:new"
```
this will tell you whether you can make calls. If that works, check the following files for data: `newtickets onholdtickets opentickets pendingtickets log` and also check if there are files in `tmpd` and `tmpl`

**Comment by Direcious** [comment]
Ah, that command was very helpful. I am receiving an authentication error. I am going to keep this issue open until I can confirm there are no other issues after authentication. Thanks 💯

**Comment by Direcious** [comment]
Hey, so the authentication issue is no longer present, thanks for that :)

Currently, using the above command shows me new tickets when I use it,
Looking at `newtickets opentickets pendingtickets log` I can see data is being populated,
`tmpd` has files within it, but `tmpl` is empty
board.html is still not being populated when I go to it, after refreshing, and after confirming that there are open tickets. Any ideas ? 😢

**Comment by spacerainbow000** [comment]
check if there is data in slatimes.html and assignees.html
check whether `cat tmpd/* | grep -v null | awk '{print $0"<br>"}'` returns anything
tmpl should have assignee information in it, can you manually run `curl -s -u $CREDENTIALS/token:$TOKEN "https://$TARGET/api/v2/tickets/${1}.json?include=users,groups"` with ${1} replaced with a ticket number?
also could you run \ls -hlaF in the directory with all your files in it, and post the output?

**Comment by Direcious** [comment]
SLAtimes.html & assignees.html are empty
The first command does not return anything

Manually running the curl command with an available ticket does return valid data.

```
total 528
drwxr-xr-x   36 supportdashboard  staff   1.2K 11 Jul 15:58 ./
drwxr-xr-x+  19 supportdashboard  staff   646B 11 Jul 13:16 ../
drwxr-xr-x   12 supportdashboard  staff   408B 30 Jun 12:23 .git/
-rw-r--r--    1 supportdashboard  staff   116B 30 Jun 12:23 .gitignore
-rwxr-xr-x    1 supportdashboard  staff   225B 30 Jun 12:23 DOAPITOUCHES*
-rw-r--r--    1 supportdashboard  staff    34K 30 Jun 12:23 LICENSE
-rw-r--r--    1 supportdashboard  staff     0B 11 Jul 15:58 SLAtimes.html
-rw-r--r--    1 supportdashboard  staff     0B 11 Jul 15:58 assignees.html
-rw-r--r--    1 supportdashboard  staff   554B 30 Jun 12:23 board.html
-rw-r--r--    1 supportdashboard  staff    20B 30 Jun 12:23 creds
-rw-r--r--    1 supportdashboard  staff    25K 30 Jun 12:23 date.js
-rwxr-xr-x    1 supportdashboard  staff   439B 30 Jun 12:23 getnewtickets*
-rwxr-xr-x    1 supportdashboard  staff   446B 30 Jun 12:23 getonholdtickets*
-rwxr-xr-x    1 supportdashboard  staff   444B 30 Jun 12:23 getopentickets*
-rwxr-xr-x    1 supportdashboard  staff   450B 30 Jun 12:23 getpendingtickets*
-rw-r--r--    1 supportdashboard  staff    85K 30 Jun 12:23 jquery-3.2.1.min.js
-rwxr-xr-x    1 supportdashboard  staff    56B 30 Jun 12:23 killserver*
-rw-r--r--    1 supportdashboard  staff    12K 11 Jul 15:58 log
-rw-r--r--    1 supportdashboard  staff     6B 11 Jul 15:58 newtickets
-rw-r--r--    1 supportdashboard  staff     1B 11 Jul 15:58 onholdtickets
-rw-r--r--    1 supportdashboard  staff   757B 11 Jul 15:58 opentickets
-rw-r--r--    1 supportdashboard  staff   600B 11 Jul 15:58 pendingtickets
-rw-r--r--    1 supportdashboard  staff   1.4K 30 Jun 12:23 prettify_json.rb
-rwxr-xr-x    1 supportdashboard  staff   637B 30 Jun 12:23 pullSLAs*
-rwxr-xr-x    1 supportdashboard  staff   1.2K 30 Jun 12:23 pullassignees*
-rw-r--r--    1 supportdashboard  staff   420B 30 Jun 12:23 quickinit
-rw-r--r--    1 supportdashboard  staff   642B 30 Jun 12:23 readme
-rw-r--r--    1 supportdashboard  staff   959B 30 Jun 12:23 srv.py
-rwxr-xr-x    1 supportdashboard  staff   157B 30 Jun 12:23 startserver*
-rw-r--r--    1 supportdashboard  staff   644B 30 Jun 12:23 style.css
-rw-r--r--    1 supportdashboard  staff    22B 10 Jul 15:51 target
-rw-r--r--    1 supportdashboard  staff   4.2K 30 Jun 12:23 timer.js
drwxr-xr-x  128 supportdashboard  staff   4.3K 11 Jul 15:58 tmpd/
drwxr-xr-x    2 supportdashboard  staff    68B  9 Jul 20:11 tmpl/
-rw-r--r--    1 supportdashboard  staff    41B 11 Jul 12:36 token
```

**Comment by spacerainbow000** [comment]
permissions on tmpd are different for you than they are for me, try:
```
getfacl tmpd
chmod 777 tmpd
```
then try
```
curl -s -u $CREDENTIALS/token:$TOKEN "https://$TARGET/api/v2/tickets/12345.json?include=slas" | ruby prettify_json.rb | grep -A3 'breach_at'
```
with 12345 replaced by a ticket number that you know has an SLA. The permissions on tmpd honestly shouldnt matter but its possible. Just to confirm, you have these things on your tickets, right?
![sla_time_indicator](https://user-images.githubusercontent.com/21026840/28089802-118268f2-663f-11e7-8931-175e2c669280.png)
give
```
./DOAPITOUCHES
```
a try as well, that should run all the api calls at once and if any of them fail you should get the output directly to your terminal. Feel free to attach `log` as well, idk if there will be anything useful in there but if doapitouches runs without throwing any errors then that means your api responses don't contain breach_at info, which if you have SLAs they totally should.
